# Generated by Django 2.0.1 on 2018-03-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('A_COD', models.FloatField()),
                ('A_NH4', models.FloatField()),
                ('A_NO2', models.FloatField()),
                ('A_NO3', models.FloatField()),
                ('A_MLSS', models.FloatField()),
                ('O1_COD', models.FloatField()),
                ('O1_NH4', models.FloatField()),
                ('O1_NO2', models.FloatField()),
                ('O1_NO3', models.FloatField()),
                ('O1_MLSS', models.FloatField()),
                ('O2_COD', models.FloatField()),
                ('O2_NH4', models.FloatField()),
                ('O2_NO2', models.FloatField()),
                ('O2_NO3', models.FloatField()),
                ('O2_MLSS', models.FloatField()),
                ('O3_COD', models.FloatField()),
                ('O3_NH4', models.FloatField()),
                ('O3_NO2', models.FloatField()),
                ('O3_NO3', models.FloatField()),
                ('O3_MLSS', models.FloatField()),
                ('O4_COD', models.FloatField()),
                ('O4_NH4', models.FloatField()),
                ('O4_NO2', models.FloatField()),
                ('O4_NO3', models.FloatField()),
                ('O4_MLSS', models.FloatField()),
            ],
        ),
    ]
