# Generated by Django 2.0.3 on 2018-03-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contamination',
            old_name='A_DO',
            new_name='A_Do',
        ),
        migrations.RenameField(
            model_name='contamination',
            old_name='Cf_DO',
            new_name='Cf_Do',
        ),
        migrations.RenameField(
            model_name='contamination',
            old_name='Ef_DO',
            new_name='Ef_Do',
        ),
        migrations.RenameField(
            model_name='contamination',
            old_name='O1_DO',
            new_name='O1_Do',
        ),
        migrations.RenameField(
            model_name='contamination',
            old_name='O2_DO',
            new_name='O2_Do',
        ),
        migrations.RenameField(
            model_name='contamination',
            old_name='O3_DO',
            new_name='O3_Do',
        ),
        migrations.RenameField(
            model_name='contamination',
            old_name='O4_DO',
            new_name='O4_Do',
        ),
    ]
