# Generated by Django 2.0.3 on 2018-03-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20180316_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contamination',
            name='Cf_Do',
        ),
        migrations.RemoveField(
            model_name='contamination',
            name='Cf_MLSS',
        ),
        migrations.RemoveField(
            model_name='contamination',
            name='Cf_Tem',
        ),
        migrations.RemoveField(
            model_name='contamination',
            name='Cf_pH',
        ),
        migrations.RemoveField(
            model_name='contamination',
            name='Ef_Do',
        ),
        migrations.RemoveField(
            model_name='contamination',
            name='Ef_MLSS',
        ),
        migrations.RemoveField(
            model_name='contamination',
            name='Ef_Tem',
        ),
        migrations.RemoveField(
            model_name='contamination',
            name='Ef_pH',
        ),
        migrations.AddField(
            model_name='contamination',
            name='Statement',
            field=models.CharField(default='This is the daily report!', max_length=200),
        ),
    ]
