from django.db import models
class contamination(models.Model):
    date=models.DateField()
    If_COD=models.FloatField()
    If_NH4=models.FloatField()
    If_NO2=models.FloatField()
    If_NO3=models.FloatField()
    A_Tem=models.FloatField()
    A_pH=models.FloatField()
    A_Do=models.FloatField()
    A_COD=models.FloatField()
    A_NH4=models.FloatField()
    A_NO2=models.FloatField()
    A_NO3=models.FloatField()
    A_MLSS=models.FloatField()
    O1_Tem=models.FloatField()
    O1_pH=models.FloatField()
    O1_Do=models.FloatField()
    O1_COD=models.FloatField()
    O1_NH4=models.FloatField()
    O1_NO2=models.FloatField()
    O1_NO3=models.FloatField()
    O1_MLSS=models.FloatField()
    O2_Tem=models.FloatField()
    O2_pH=models.FloatField()
    O2_Do=models.FloatField()
    O2_COD=models.FloatField()
    O2_NH4=models.FloatField()
    O2_NO2=models.FloatField()
    O2_NO3=models.FloatField()
    O2_MLSS=models.FloatField()
    O3_Tem=models.FloatField()
    O3_pH=models.FloatField()
    O3_Do=models.FloatField()
    O3_COD=models.FloatField()
    O3_NH4=models.FloatField()
    O3_NO2=models.FloatField()
    O3_NO3=models.FloatField()
    O3_MLSS=models.FloatField()
    O4_Tem=models.FloatField()
    O4_pH=models.FloatField()
    O4_Do=models.FloatField()
    O4_COD=models.FloatField()
    O4_NH4=models.FloatField()
    O4_NO2=models.FloatField()
    O4_NO3=models.FloatField()
    O4_MLSS=models.FloatField()
    Ef_COD=models.FloatField()
    Ef_NH4=models.FloatField()
    Ef_NO2=models.FloatField()
    Ef_NO3=models.FloatField()
    Statement=models.CharField(default='This is the daily report!',max_length=200)
    def __str__(self):
        return str(self.date)
    

# Create your models here.
